import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/base/Navbar";
import { Fredoka, Poppins } from "next/font/google";
import Footer from "@/components/base/Footer";

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
  weight: ["400", "500", "600", "700"],
  fallback: ["sans-serif"],
});

const roboto = Poppins({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "500", "700"],
  fallback: ["sans-serif"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${roboto.variable} ${fredoka.variable} antialiased`}>
        <Navbar />
        <main className="md:px-0 px-3">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
