/* eslint-disable react/no-unescaped-entities */

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | RWahab Movers UAE",
  description:
    "RWahab Movers UAE Privacy Policy. Our privacy policy outlines our policies and procedures regarding the collection, use, and disclosure of your information when you use our services.",
  alternates: {
    canonical: `${process.env.PUBLIC_URL}/privacy-policy`,
  },
  openGraph: {
    type: "website",
    locale: "en-AE",
    countryName: "United Arab Emirates",
    emails: "wk0131839@gamil.com",
    faxNumbers: "+971503806855",
    phoneNumbers: "+971503806855",
    siteName: "RWahab Movers UAE",
    title: "Privacy Policy | RWahab Movers UAE",
    description:
      "RWahab Movers UAE Privacy Policy. Our privacy policy outlines our policies and procedures regarding the collection, use, and disclosure of your information when you use our services.",
    url: `${process.env.PUBLIC_URL}/privacy-policy`,
    images: `${process.env.PUBLIC_URL}/images/privacy-policy.jpg`,
  },
};
const PrivacyPolicy: React.FC = () => {
  const formattedDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <section id="privacy-policy" className="max-w-4xl mx-auto mt-44 px-3">
      <h1>Privacy Policy</h1>
      <p>
        <strong>Last updated: {formattedDate}</strong>
      </p>

      <p>
        This Privacy Policy outlines our policies and procedures regarding the
        collection, use, and disclosure of your information when you use our
        services. It also informs you about your privacy rights and how the law
        protects you.
      </p>
      <p>
        We utilize your data to provide and enhance our services. By using our
        services, you consent to the collection and use of information in
        accordance with this Privacy Policy.
      </p>

      <h2>Interpretation and Definitions</h2>

      <h3>Interpretation</h3>
      <p>
        The words with initial capital letters have meanings defined under the
        following conditions. The definitions below shall have the same meaning
        regardless of whether they appear in singular or plural forms.
      </p>

      <h3>Definitions</h3>
      <ul>
        <li>
          <strong>Account:</strong> A unique account created for you to access
          our services or certain parts of our services.
        </li>
        <li>
          <strong>Affiliate:</strong> An entity that controls, is controlled by,
          or is under common control with a party. &quot;Control&quot; means
          ownership of 50% or more of the shares, equity interest, or other
          securities entitled to vote for the election of directors or other
          managing authorities.
        </li>
        <li>
          <strong>Company:</strong> Refers to RWahab Movers UAE (referred to as
          &quot;the Company,&quot; "We,&quot; "Us," or "Our" in this Agreement),
          located at Building No. 12, Street 4, Al Yarmook, Sharjah.
        </li>
        <li>
          <strong>Cookies:</strong> Small files placed on your computer, mobile
          device, or other devices by a website, containing details of your
          browsing history on that website, among other uses.
        </li>
        <li>
          <strong>Country:</strong> Refers to the United Arab Emirates.
        </li>
        <li>
          <strong>Device:</strong> Any device that can access the service, such
          as a computer, cellphone, or tablet.
        </li>
        <li>
          <strong>Personal Data:</strong> Any information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Service:</strong> Refers to the website.
        </li>
        <li>
          <strong>Service Provider:</strong> Any natural or legal person who
          processes data on behalf of the Company. This includes third-party
          companies or individuals employed by the Company to facilitate the
          service, provide the service on the Company's behalf, perform services
          related to the service, or assist the Company in analyzing how the
          service is used.
        </li>
        <li>
          <strong>Usage Data:</strong> Data collected automatically, either
          generated by the use of the service or from the service's
          infrastructure itself (e.g., the duration of a page visit).
        </li>
        <li>
          <strong>Website:</strong> Refers to RWahab Movers UAE, accessible from{" "}
          <a
            href="https://rwahabmoversuae.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            https://rwahabmoversuae.com/
          </a>
          .
        </li>
        <li>
          <strong>You:</strong> The individual accessing or using the service,
          or the company or other legal entity on behalf of which such
          individual is accessing or using the service, as applicable.
        </li>
      </ul>

      <h2>Collecting and Using Your Data</h2>

      <h3>Types of Data Collected</h3>

      <h4>Personal Data</h4>
      <p>
        While using our service, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, state, province, and city</li>
      </ul>

      <h4>Usage Data</h4>
      <p>
        Usage Data is collected automatically when using the service. This data
        may include information such as your device's Internet Protocol address
        (e.g., IP address), browser type, browser version, the pages of our
        service that you visit, the time and date of your visit, the time spent
        on those pages, unique device identifiers, and other diagnostic data.
      </p>
      <p>
        When you access the service via a mobile device, we may collect certain
        information automatically, including, but not limited to, the type of
        mobile device you use, your mobile device's unique ID, the IP address of
        your mobile device, your mobile operating system, the type of mobile
        Internet browser you use, unique device identifiers, and other
        diagnostic data.
      </p>
      <p>
        We may also collect information that your browser sends whenever you
        visit our service or access it via a mobile device.
      </p>

      <h3>Tracking Technologies and Cookies</h3>
      <p>
        We use cookies and similar tracking technologies to monitor activity on
        our service and store certain information. Tracking technologies used
        may include beacons, tags, and scripts to collect and track information
        and to improve and analyze our service. The technologies we utilize may
        include:
      </p>
      <ul>
        <li>
          <strong>Cookies or Browser Cookies:</strong> A cookie is a small file
          placed on your device. You can instruct your browser to refuse all
          cookies or to indicate when a cookie is being sent. However, if you do
          not accept cookies, you may not be able to use some parts of our
          service. Unless you have adjusted your browser settings to reject
          cookies, our service may use cookies.
        </li>
        <li>
          <strong>Web Beacons:</strong> Certain sections of our service and our
          emails may contain small electronic files known as web beacons (also
          referred to as clear gifs, pixel tags, and single-pixel gifs). These
          allow the Company, for example, to count users who have visited those
          pages or opened an email and for other related website statistics
          (such as recording the popularity of a certain section and verifying
          system and server integrity).
        </li>
      </ul>
      <p>
        Cookies can be classified as "Persistent" or "Session" cookies.
        Persistent cookies remain on your personal computer or mobile device
        when you go offline, while session cookies are deleted as soon as you
        close your web browser.
      </p>
    </section>
  );
};

export default PrivacyPolicy;
